Release/0.1.0.beta1
mysuperai/superai-sdk pull request #32
Opened 2021-08-18 18:07 UTC by engarpe

## 🛠 Changes
-
-

## 🧪 How is this tested?

## 🗒️ Release Notes
-

### User-facing change?
- [ ] No. Skip the rest of this section
- [ ] Yes. Give a description of this change to be included in the release notes.

### What component(s) does this PR affect?

**Components**
- [ ] CLI
- [ ] APIs
- [ ] DataProgram SDK

**How should the PR be classified in the release notes? Choose one:**
- [ ] `breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `bug`-fix - A user-facing bug fix worth mentioning in the release notes
- [ ] `documentation` - A user-facing documentation change worth mentioning in the release notes

2021-08-18 19:01 UTC, ankitmishra262 requested changes
Minor changes, I will push the fixes.

2021-08-18 19:05 UTC, ankitmishra262 commented on superai/meta_ai/dockerizer/sagemaker_endpoint.py
> +    )
Removed

2021-08-18 19:05 UTC, ankitmishra262 commented on superai/meta_ai/dockerizer/sagemaker_endpoint.py
> +        # arn_role = "arn:aws:iam::185169359328:role/service-role/AmazonSageMaker-ExecutionRole-20180117T160866"
removed

2021-08-18 19:06 UTC, ankitmishra262 commented on superai/meta_ai/dockerizer/sagemaker_endpoint.py
> +    # arn_role = "arn:aws:iam::185169359328:role/service-role/AmazonSageMaker-ExecutionRole-20180117T160866"
removed

2021-08-18 19:06 UTC, ankitmishra262 approved these changes

2021-08-19 12:13 UTC, lpfann approved these changes

2021-08-19 12:16 UTC, ankitmishra262 commented
@engarpe another point to add on to, which you don't want to handle during your break, I am not authorized to merge the PR. Would it be good to give that permission to a few of us?

2021-08-20 11:28 UTC, merged